// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7XIwbJmZ5oJYG6LiVAVjrWFvxbwP6Z2E',
    appId: '1:139217094496:web:1a5d2ebe19633bcece8005',
    messagingSenderId: '139217094496',
    projectId: 'tigaad-9957b',
    authDomain: 'tigaad-9957b.firebaseapp.com',
    storageBucket: 'tigaad-9957b.appspot.com',
    measurementId: 'G-HTNXWG97R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdxJ22oLSiJ3bXnug44GCYb-KLcLw94g',
    appId: '1:139217094496:android:d5f2361226d54212ce8005',
    messagingSenderId: '139217094496',
    projectId: 'tigaad-9957b',
    storageBucket: 'tigaad-9957b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-KnZeENtUyv2nYnUpQPY0AQ9EqKB6P3k',
    appId: '1:139217094496:ios:a0cdb9b921869b1dce8005',
    messagingSenderId: '139217094496',
    projectId: 'tigaad-9957b',
    storageBucket: 'tigaad-9957b.appspot.com',
    iosClientId: '139217094496-pta1so52m9ho972mc5utc3t6pgg56cu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-KnZeENtUyv2nYnUpQPY0AQ9EqKB6P3k',
    appId: '1:139217094496:ios:a0cdb9b921869b1dce8005',
    messagingSenderId: '139217094496',
    projectId: 'tigaad-9957b',
    storageBucket: 'tigaad-9957b.appspot.com',
    iosClientId: '139217094496-pta1so52m9ho972mc5utc3t6pgg56cu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhirApp',
  );
}
